global:
  ingressSubdomain: test-og.us-south.containers.appdomain.cloud
  tlsSecretName: mooc-team-one

inventory-management-svc-og:
  replicaCount: 2
  
  ingress:
    enabled: true
    tlsSecretName: mooc-team-one